# Generated by Django 4.0.5 on 2022-06-13 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='task',
            name='lastDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 13, 14, 49, 8, 440307, tzinfo=utc), verbose_name='Last Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='streakOrNot',
            field=models.TextField(blank=True, default='0,'),
        ),
        migrations.AddField(
            model_name='task',
            name='streakSum',
            field=models.IntegerField(blank=True, default=0, verbose_name='Streak Sum'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Title'),
        ),
    ]
