# Generated by Django 4.0.5 on 2022-06-14 04:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_remove_task_name_task_description_task_lastdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='currentStreak',
            field=models.IntegerField(blank=True, default=0, verbose_name='Current Streak'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lastDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 14, 4, 43, 18, 868503, tzinfo=utc), verbose_name='Last Date'),
        ),
    ]
