# Generated by Django 4.0.5 on 2022-06-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_task_currentstreak_alter_task_lastdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lastDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last Date'),
        ),
    ]
