# Generated by Django 4.0.5 on 2022-06-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_alter_task_lastdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isDoneToday',
            field=models.BooleanField(default=False, verbose_name='isDoneToday'),
        ),
    ]
